### ISSUE TITLE
[FR] TODO LIST

### ISSUE THREAD

**Issue by vrichv** [vrichv/my-tv-0#2]
### 检查清单

- [X] 明白上述声明
- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

TODOs

### Usability

- [x]  Support Kitkat
- [x] Use GitHub as the upgrade service backend
- [x]  Compatible with any https certificates on Android 4.x, especially new certificates from GitHub and Let's Encrypt
- [x]  UI displays detailed error information
- [x]  Set the default port of the http server to a fixed value 10086
- [x]  Enhance the compatibility of IPTV playback sources, such as flv/mpeg format.

### SHARP TV

- [x] Solve the problem caused by apps launching multiple times after reboot on Sharp TV
- [ ] H265 video decoding failure

### Security

- [x] All binary resources in the source code must be verifiable and self-distributable as documented
- [ ]  Remove github  proxy
- [ ] The current version ignores https certificates and is not secure. Integrate the latest certificate internally and enable certificate validation

### Dev

- [x]  Support Jellybean

**Comment by smgfw** [comment]
分支更新，赞！
固定端口，赞赞！！
支持Jellybean，赞赞赞！！！

**Comment by mars315** [comment]
源是要自己搞定么？软件有个默认的源，但是基本都看不了

**Comment by smgfw** [comment]
> 源是要自己搞定么？软件有个默认的源，但是基本都看不了

我用的源来自 @yuechan ，非常好用。或者 @fangmingming 的ipv6

**Comment by mars315** [comment]
> > 源是要自己搞定么？软件有个默认的源，但是基本都看不了
> 
> 我用的源来自 @YueChan ，非常好用。或者 @fangmingming 的ipv6

感谢

**Comment by YueChan** [comment]
做了一点小小的工作！

**Comment by vrichv** [comment]
> 做了一点小小的工作！

大佬好，把默认源设置成你的 :)

**Comment by vrichv** [comment]
> 做了一点小小的工作！

@YueChan 大佬好，把默认源设置成你的 :)

**Comment by andandroidor** [comment]
亲测可用https://github.com/andandroidor/ourtv

**Comment by dxxjg** [comment]
> 亲测可用https://github.com/andandroidor/ourtv

@vrichv 给他向下兼容一下😄。他这个套壳思路挺牛逼。

**Comment by vrichv** [comment]
不开源的东西就不要往github上面放了，侮辱了这个平台
这种来临不明不开源的app，只会使你家设备变成僵尸网络的一部分

**Comment by andandroidor** [comment]
> 不开源的东西就不要往github上面放了，侮辱了这个平台 这种来历不明不开源的app，只会使你家设备变成僵尸网络的一部分


说话可得讲证据啊 搞不定播放源就这样污蔑么？

**Comment by iceloon** [comment]
更新了源 无法保存呀  返回 退出  都变成之前的了

**Comment by cqbf** [comment]
大佬，考虑过提交pr吗？直接让原版实现兼容，也减少您的开发压力。

**Comment by vrichv** [comment]
> 更新了源 无法保存呀 返回 退出 都变成之前的了
看看是不是原版的这个bug
https://github.com/lizongying/my-tv-0/issues/74

**Comment by cqbf** [comment]
> > 大佬，考虑过提交pr吗？直接让原版实现兼容，也减少您的开发压力。
> 
> 应该是大神要先建个新的kitkat分支，我才能创个PR合去新分支

懂了。我去推动一下哈哈

**Comment by cqbf** [comment]
LZY大佬估计又停一段时间。大佬辛苦一下，能出一版1.3.7jb吗？十分想试试最新版。

**Comment by cqbf** [comment]
> > 大佬，考虑过提交pr吗？直接让原版实现兼容，也减少您的开发压力。
> 
> 应该是大神要先建个新的kitkat分支，我才能创个PR合去新分支

大佬，有进展了：LZY大神已经添加KK和JB分支。
 https://github.com/lizongying/my-tv-0/issues/104#issuecomment-2336569554

**Comment by cqbf** [comment]
感谢大佬贡献4.4代码。也期待大佬能支持4.2~4.3。点赞
